-- WorshipFlow — Phase 1: core schema
-- Run this in Supabase Dashboard -> SQL Editor -> New Query, paste, click Run.
-- (Or, if you use the Supabase CLI later, this file runs automatically via
-- `supabase db push` since it lives in supabase/migrations/.)

create extension if not exists pgcrypto;

-- Enum types -----------------------------------------------------------

create type license_status as enum ('unused', 'active', 'expired', 'revoked');
create type team_role as enum ('hotu', 'bawmtu', 'member');
create type roster_status as enum ('draft', 'published');
create type assignment_response as enum ('pending', 'accepted', 'declined');

-- License plans ----------------------------------------------------------
-- The catalog of plans you (the Owner) can issue keys against. duration_in_days
-- is null for plans that never expire (Lifetime).

create table public.license_plans (
  plan_code text primary key,
  label text not null,
  duration_in_days integer, -- null = never expires
  created_at timestamptz not null default now()
);

-- Churches -----------------------------------------------------------------
-- Created via the "Register Your Church" flow once a valid product key is
-- redeemed. license_key_id is added with a foreign key below, after
-- license_keys exists (the two tables reference each other).

create table public.churches (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact_email text not null,
  language_code text not null default 'en',
  license_key_id uuid, -- FK added below
  created_at timestamptz not null default now()
);

-- License keys ---------------------------------------------------------
-- Generated by the Owner. church_id stays null until the key is redeemed.

create table public.license_keys (
  id uuid primary key default gen_random_uuid(),
  key_code text not null unique,
  plan_code text not null references public.license_plans (plan_code),
  issued_to_email text not null,
  church_id uuid references public.churches (id) on delete set null,
  status license_status not null default 'unused',
  created_at timestamptz not null default now(),
  activated_at timestamptz,
  expires_at timestamptz
);

alter table public.churches
  add constraint churches_license_key_id_fkey
  foreign key (license_key_id) references public.license_keys (id) on delete set null;

-- Users ----------------------------------------------------------------
-- One row per Supabase Auth user. church_id is null only for the Owner
-- account (which does not belong to any single church).
--
-- is_owner marks the single account that is you, the app Owner. It is
-- deliberately NOT editable through the normal app API — see the column
-- privilege grants in 0002_functions_and_rls.sql, and the manual
-- instructions for turning it on for your own account.
--
-- is_church_admin marks the person who registered a church (or who an
-- existing Admin promotes later). This isn't one of the columns you listed,
-- but "make the registering person that church's Admin" needs somewhere to
-- live, and it belongs on the user, alongside is_owner.

create table public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  church_id uuid references public.churches (id) on delete set null,
  email text not null,
  full_name text,
  is_owner boolean not null default false,
  is_church_admin boolean not null default false,
  created_at timestamptz not null default now()
);

-- Teams ------------------------------------------------------------------

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  name text not null,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.team_members (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  role team_role not null default 'member',
  created_at timestamptz not null default now(),
  unique (team_id, user_id)
);

create table public.team_positions (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams (id) on delete cascade,
  label text not null,
  display_order integer not null default 0
);

-- Service types & occurrences --------------------------------------------

create table public.service_types (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  name text not null,
  default_weekday integer check (default_weekday between 0 and 6), -- 0 = Sunday
  default_start_time time,
  default_location text
);

create table public.service_occurrences (
  id uuid primary key default gen_random_uuid(),
  service_type_id uuid not null references public.service_types (id) on delete cascade,
  date date not null,
  note text
);

-- Rosters ------------------------------------------------------------------

create table public.rosters (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams (id) on delete cascade,
  month integer not null check (month between 1 and 12),
  year integer not null,
  status roster_status not null default 'draft',
  created_at timestamptz not null default now(),
  unique (team_id, month, year)
);

create table public.roster_assignments (
  id uuid primary key default gen_random_uuid(),
  roster_id uuid not null references public.rosters (id) on delete cascade,
  service_occurrence_id uuid not null references public.service_occurrences (id) on delete cascade,
  team_position_id uuid not null references public.team_positions (id) on delete cascade,
  user_id uuid references public.users (id) on delete set null,
  response assignment_response not null default 'pending',
  created_at timestamptz not null default now()
);

-- Library & planning, all scoped to one church each -----------------------

create table public.songs (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  title text not null,
  lyrics text,
  created_at timestamptz not null default now()
);

create table public.media_assets (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  name text not null,
  storage_path text,
  kind text,
  created_at timestamptz not null default now()
);

create table public.service_items (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  service_occurrence_id uuid references public.service_occurrences (id) on delete set null,
  title text not null,
  item_type text,
  display_order integer not null default 0
);

-- Helpful indexes ----------------------------------------------------------

create index on public.license_keys (church_id);
create index on public.users (church_id);
create index on public.teams (church_id);
create index on public.team_members (user_id);
create index on public.team_positions (team_id);
create index on public.service_types (church_id);
create index on public.service_occurrences (service_type_id);
create index on public.rosters (team_id);
create index on public.roster_assignments (roster_id);
create index on public.roster_assignments (user_id);
create index on public.songs (church_id);
create index on public.media_assets (church_id);
create index on public.service_items (church_id);
-- WorshipFlow — Phase 1: helper functions, Row Level Security, and column locks
-- Run this in the Supabase SQL Editor AFTER 0001_schema.sql.

-- Helper functions ---------------------------------------------------------
-- security definer + a fixed search_path lets these look up the CALLING
-- user's own row in public.users without re-triggering RLS on that table
-- (which would otherwise cause infinite recursion), while never letting a
-- caller pass in someone else's id.

create or replace function public.current_church_id()
returns uuid
language sql
security definer
set search_path = public
stable
as $$
  select church_id from public.users where id = auth.uid();
$$;

create or replace function public.is_owner()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select is_owner from public.users where id = auth.uid()), false);
$$;

create or replace function public.is_church_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select is_church_admin from public.users where id = auth.uid()), false);
$$;

-- Turn on Row Level Security everywhere ------------------------------------
-- With RLS on and no matching policy, a table defaults to "nobody can see or
-- touch this row" — so every table below needs explicit policies, which is
-- exactly the safe default we want.

alter table public.license_plans enable row level security;
alter table public.license_keys enable row level security;
alter table public.churches enable row level security;
alter table public.users enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.team_positions enable row level security;
alter table public.service_types enable row level security;
alter table public.service_occurrences enable row level security;
alter table public.rosters enable row level security;
alter table public.roster_assignments enable row level security;
alter table public.songs enable row level security;
alter table public.media_assets enable row level security;
alter table public.service_items enable row level security;

-- Licensing data: Owner only -------------------------------------------
-- Registration itself (checking a key, marking it active) happens through a
-- server action using the service_role key, which bypasses RLS entirely —
-- so a brand-new person with no account yet can still redeem a key. These
-- policies only govern what a logged-in, non-owner person can see, which is
-- nothing.

create policy "owner manages license plans" on public.license_plans
  for all using (public.is_owner()) with check (public.is_owner());

create policy "owner manages license keys" on public.license_keys
  for all using (public.is_owner()) with check (public.is_owner());

-- Churches ---------------------------------------------------------------
-- Members of a church can see their own church's record; the Owner can see
-- every church (needed for the Owner Console in Phase 2). Creating a church
-- happens via the service-role registration flow, not directly by users, so
-- there is no INSERT policy for logged-in users here.

create policy "see own church or all as owner" on public.churches
  for select using (id = public.current_church_id() or public.is_owner());

create policy "admins update own church" on public.churches
  for update using (id = public.current_church_id() and public.is_church_admin())
  with check (id = public.current_church_id() and public.is_church_admin());

-- Users --------------------------------------------------------------------
-- Everyone can see their own row and their churchmates' rows (needed to show
-- names in team rosters); the Owner can see everyone. Creating a user row
-- happens via the service-role registration/invite flow only — there is
-- deliberately no INSERT policy for the authenticated role.

create policy "see self, churchmates, or all as owner" on public.users
  for select using (
    id = auth.uid()
    or (church_id is not null and church_id = public.current_church_id())
    or public.is_owner()
  );

create policy "update own profile" on public.users
  for update using (id = auth.uid()) with check (id = auth.uid());

-- Column-level lock on is_owner / is_church_admin / church_id --------------
-- RLS controls which ROWS a policy allows; it can't by itself stop someone
-- from editing specific COLUMNS on a row they're otherwise allowed to
-- update. So on top of the policy above, we revoke UPDATE on the whole
-- table from ordinary logged-in users and re-grant it for only the columns
-- that are safe for someone to change about themselves. is_owner,
-- is_church_admin, and church_id can then only ever be changed by the
-- service_role key (server actions) or directly in the Supabase dashboard —
-- never through the app's normal UI.

revoke update on public.users from authenticated;
grant update (full_name) on public.users to authenticated;

-- Teams, positions, service types: scoped to one church ---------------
-- Phase 1 keeps this simple — any signed-in member of a church can manage
-- their church's teams/positions/service types. Phase 4 tightens this down
-- to Admin-only (for teams/service types) and Hotu/Bawmtu-only (for a
-- team's own positions), per the roadmap.

create policy "church members manage their teams" on public.teams
  for all using (church_id = public.current_church_id())
  with check (church_id = public.current_church_id());

create policy "church members manage team positions" on public.team_positions
  for all using (team_id in (select id from public.teams where church_id = public.current_church_id()))
  with check (team_id in (select id from public.teams where church_id = public.current_church_id()));

create policy "church members manage team members" on public.team_members
  for all using (team_id in (select id from public.teams where church_id = public.current_church_id()))
  with check (team_id in (select id from public.teams where church_id = public.current_church_id()));

create policy "church members manage service types" on public.service_types
  for all using (church_id = public.current_church_id())
  with check (church_id = public.current_church_id());

create policy "church members manage service occurrences" on public.service_occurrences
  for all using (service_type_id in (select id from public.service_types where church_id = public.current_church_id()))
  with check (service_type_id in (select id from public.service_types where church_id = public.current_church_id()));

-- Rosters --------------------------------------------------------------

create policy "church members manage rosters" on public.rosters
  for all using (team_id in (select id from public.teams where church_id = public.current_church_id()))
  with check (team_id in (select id from public.teams where church_id = public.current_church_id()));

create policy "church members manage roster assignments" on public.roster_assignments
  for all using (
    roster_id in (
      select r.id from public.rosters r
      join public.teams t on t.id = r.team_id
      where t.church_id = public.current_church_id()
    )
  )
  with check (
    roster_id in (
      select r.id from public.rosters r
      join public.teams t on t.id = r.team_id
      where t.church_id = public.current_church_id()
    )
  );

-- Library & service planning ------------------------------------------

create policy "church members manage songs" on public.songs
  for all using (church_id = public.current_church_id())
  with check (church_id = public.current_church_id());

create policy "church members manage media assets" on public.media_assets
  for all using (church_id = public.current_church_id())
  with check (church_id = public.current_church_id());

create policy "church members manage service items" on public.service_items
  for all using (church_id = public.current_church_id())
  with check (church_id = public.current_church_id());
-- WorshipFlow — Phase 1: seed the four starting license plans.
-- Run this in the Supabase SQL Editor AFTER 0001 and 0002.
-- Safe to re-run: it updates the label/duration if the plan_code already exists
-- instead of erroring out.

insert into public.license_plans (plan_code, label, duration_in_days) values
  ('trial_14', '14-Day Trial', 14),
  ('monthly', 'Monthly', 30),
  ('yearly', 'Yearly', 365),
  ('lifetime', 'Lifetime', null)
on conflict (plan_code) do update
  set label = excluded.label,
      duration_in_days = excluded.duration_in_days;
-- WorshipFlow — Phase 1: the "redeem a product key" function.
-- Run this in the Supabase SQL Editor AFTER 0001, 0002, and 0003.
--
-- This does the whole "Register Your Church" step in one atomic database
-- transaction (check key -> create church -> mark key active -> make the
-- registering person Admin), so nothing gets half-done if something fails
-- partway through, and two people can't both redeem the same key at the
-- same instant (the "for update" line below locks the key's row while it
-- checks it).
--
-- SECURITY DEFINER means this function runs with the permissions of the
-- person who created it (the database owner), not the caller — that's what
-- lets it write to license_keys and users even though ordinary logged-in
-- users aren't allowed to touch those tables directly. Only the server
-- (using the service_role key, from a Next.js Server Action) is granted
-- permission to call it — never the browser.

create or replace function public.redeem_license_key(
  p_key_code text,
  p_church_name text,
  p_contact_email text,
  p_language_code text,
  p_user_id uuid,
  p_user_email text,
  p_full_name text
)
returns table (church_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key public.license_keys%rowtype;
  v_church_id uuid;
  v_duration integer;
  v_expires_at timestamptz;
begin
  select * into v_key
  from public.license_keys
  where key_code = p_key_code
  for update;

  if v_key.id is null then
    raise exception 'INVALID_KEY';
  end if;

  if v_key.status <> 'unused' then
    raise exception 'KEY_ALREADY_USED';
  end if;

  if v_key.expires_at is not null and v_key.expires_at < now() then
    raise exception 'KEY_EXPIRED';
  end if;

  select duration_in_days into v_duration
  from public.license_plans
  where plan_code = v_key.plan_code;

  if v_duration is null then
    v_expires_at := null; -- Lifetime
  else
    v_expires_at := now() + (v_duration || ' days')::interval;
  end if;

  insert into public.churches (name, contact_email, language_code)
  values (p_church_name, p_contact_email, coalesce(p_language_code, 'en'))
  returning id into v_church_id;

  update public.license_keys
  set church_id = v_church_id,
      status = 'active',
      activated_at = now(),
      expires_at = v_expires_at
  where id = v_key.id;

  update public.churches
  set license_key_id = v_key.id
  where id = v_church_id;

  insert into public.users (id, church_id, email, full_name, is_owner, is_church_admin)
  values (p_user_id, v_church_id, p_user_email, p_full_name, false, true)
  on conflict (id) do update
    set church_id = excluded.church_id,
        full_name = excluded.full_name,
        is_church_admin = true;

  return query select v_church_id;
end;
$$;

revoke all on function public.redeem_license_key(text, text, text, text, uuid, text, text) from public;
grant execute on function public.redeem_license_key(text, text, text, text, uuid, text, text) to service_role;
