-- WorshipFlow — Phase 1: core schema
-- Run this in Supabase Dashboard -> SQL Editor -> New Query, paste, click Run.
-- (Or, if you use the Supabase CLI later, this file runs automatically via
-- `supabase db push` since it lives in supabase/migrations/.)

create extension if not exists pgcrypto;

-- Enum types -----------------------------------------------------------

create type license_status as enum ('unused', 'active', 'expired', 'revoked');
create type team_role as enum ('hotu', 'bawmtu', 'member');
create type roster_status as enum ('draft', 'published');
create type assignment_response as enum ('pending', 'accepted', 'declined');

-- License plans ----------------------------------------------------------
-- The catalog of plans you (the Owner) can issue keys against. duration_in_days
-- is null for plans that never expire (Lifetime).

create table public.license_plans (
  plan_code text primary key,
  label text not null,
  duration_in_days integer, -- null = never expires
  created_at timestamptz not null default now()
);

-- Churches -----------------------------------------------------------------
-- Created via the "Register Your Church" flow once a valid product key is
-- redeemed. license_key_id is added with a foreign key below, after
-- license_keys exists (the two tables reference each other).

create table public.churches (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact_email text not null,
  language_code text not null default 'en',
  license_key_id uuid, -- FK added below
  created_at timestamptz not null default now()
);

-- License keys ---------------------------------------------------------
-- Generated by the Owner. church_id stays null until the key is redeemed.

create table public.license_keys (
  id uuid primary key default gen_random_uuid(),
  key_code text not null unique,
  plan_code text not null references public.license_plans (plan_code),
  issued_to_email text not null,
  church_id uuid references public.churches (id) on delete set null,
  status license_status not null default 'unused',
  created_at timestamptz not null default now(),
  activated_at timestamptz,
  expires_at timestamptz
);

alter table public.churches
  add constraint churches_license_key_id_fkey
  foreign key (license_key_id) references public.license_keys (id) on delete set null;

-- Users ----------------------------------------------------------------
-- One row per Supabase Auth user. church_id is null only for the Owner
-- account (which does not belong to any single church).
--
-- is_owner marks the single account that is you, the app Owner. It is
-- deliberately NOT editable through the normal app API — see the column
-- privilege grants in 0002_functions_and_rls.sql, and the manual
-- instructions for turning it on for your own account.
--
-- is_church_admin marks the person who registered a church (or who an
-- existing Admin promotes later). This isn't one of the columns you listed,
-- but "make the registering person that church's Admin" needs somewhere to
-- live, and it belongs on the user, alongside is_owner.

create table public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  church_id uuid references public.churches (id) on delete set null,
  email text not null,
  full_name text,
  is_owner boolean not null default false,
  is_church_admin boolean not null default false,
  created_at timestamptz not null default now()
);

-- Teams ------------------------------------------------------------------

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  name text not null,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.team_members (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  role team_role not null default 'member',
  created_at timestamptz not null default now(),
  unique (team_id, user_id)
);

create table public.team_positions (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams (id) on delete cascade,
  label text not null,
  display_order integer not null default 0
);

-- Service types & occurrences --------------------------------------------

create table public.service_types (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  name text not null,
  default_weekday integer check (default_weekday between 0 and 6), -- 0 = Sunday
  default_start_time time,
  default_location text
);

create table public.service_occurrences (
  id uuid primary key default gen_random_uuid(),
  service_type_id uuid not null references public.service_types (id) on delete cascade,
  date date not null,
  note text
);

-- Rosters ------------------------------------------------------------------

create table public.rosters (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams (id) on delete cascade,
  month integer not null check (month between 1 and 12),
  year integer not null,
  status roster_status not null default 'draft',
  created_at timestamptz not null default now(),
  unique (team_id, month, year)
);

create table public.roster_assignments (
  id uuid primary key default gen_random_uuid(),
  roster_id uuid not null references public.rosters (id) on delete cascade,
  service_occurrence_id uuid not null references public.service_occurrences (id) on delete cascade,
  team_position_id uuid not null references public.team_positions (id) on delete cascade,
  user_id uuid references public.users (id) on delete set null,
  response assignment_response not null default 'pending',
  created_at timestamptz not null default now()
);

-- Library & planning, all scoped to one church each -----------------------

create table public.songs (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  title text not null,
  lyrics text,
  created_at timestamptz not null default now()
);

create table public.media_assets (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  name text not null,
  storage_path text,
  kind text,
  created_at timestamptz not null default now()
);

create table public.service_items (
  id uuid primary key default gen_random_uuid(),
  church_id uuid not null references public.churches (id) on delete cascade,
  service_occurrence_id uuid references public.service_occurrences (id) on delete set null,
  title text not null,
  item_type text,
  display_order integer not null default 0
);

-- Helpful indexes ----------------------------------------------------------

create index on public.license_keys (church_id);
create index on public.users (church_id);
create index on public.teams (church_id);
create index on public.team_members (user_id);
create index on public.team_positions (team_id);
create index on public.service_types (church_id);
create index on public.service_occurrences (service_type_id);
create index on public.rosters (team_id);
create index on public.roster_assignments (roster_id);
create index on public.roster_assignments (user_id);
create index on public.songs (church_id);
create index on public.media_assets (church_id);
create index on public.service_items (church_id);
